(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var m=this||self;function n(){var a=m.navigator;return a&&(a=a.userAgent)?a:""}function p(a){return-1!=n().indexOf(a)};function q(a){q[" "](a);return a}q[" "]=function(){};var aa=p("Trident")||p("MSIE"),ba=p("Gecko")&&!(-1!=n().toLowerCase().indexOf("webkit")&&!p("Edge"))&&!(p("Trident")||p("MSIE"))&&!p("Edge"),ca=-1!=n().toLowerCase().indexOf("webkit")&&!p("Edge");var da={},r=null; 
function ea(a){var b;void 0===b&&(b=0);if(!r){r={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var e=c.concat(d[f].split(""));da[f]=e;for(var g=0;g<e.length;g++){var l=e[g];void 0===r[l]&&(r[l]=g)}}}b=da[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(f=e=0;e<a.length-2;e+=3){var k=a[e],h=a[e+1];l=a[e+2];g=b[k>>2];k=b[(k&3)<<4|h>>4];h=b[(h&15)<<2|l>>6];l=b[l&63];c[f++]=g+k+h+l}g=0;l=d;switch(a.length-e){case 2:g= 
a[e+1],l=b[(g&15)<<2]||d;case 1:a=a[e],c[f]=b[a>>2]+b[(a&3)<<4|g>>4]+l+d}return c.join("")};var fa="undefined"!==typeof Uint8Array,la={};let ma;var t=class{constructor(a){if(la!==la)throw Error("illegal external caller");this.O=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}isEmpty(){return null==this.O}};const w=Symbol(void 0);function x(a,b){Object.isFrozen(a)||(w?a[w]|=b:void 0!==a.o?a.o|=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function y(a){let b;w?b=a[w]:b=a.o;return null==b?0:b}function z(a,b){w?a[w]=b:void 0!==a.o?a.o=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function G(a){return a?!!(y(a)&2):!1}function na(a,b){z(b,(y(a)|18)&-33)};var H={};function I(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var oa=Object,pa=oa.freeze,qa=[];x(qa,3);var ra=pa.call(oa,qa);function sa(a){if(G(a.i))throw Error("Cannot mutate an immutable Message");};function ta(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(fa&&null!=a&&a instanceof Uint8Array)return ea(a);if(a instanceof t){const b=a.O;return null==b?"":"string"===typeof b?b:a.O=ea(b)}}}return a};function ua(a,b,c,d){if(null!=a){if(Array.isArray(a))a=va(a,b,c,void 0!==d);else if(I(a)){const f={};for(let e in a)f[e]=ua(a[e],b,c,d);a=f}else a=b(a,d);return a}}function va(a,b,c,d){d=d?!!(y(a)&16):void 0;const f=Array.prototype.slice.call(a);c(a,f);for(a=0;a<f.length;a++)f[a]=ua(f[a],b,c,d);return f}function wa(a){return a.N===H?a.toJSON():ta(a)}function xa(){};function J(a,b,c=!1){return-1===b?null:b>=a.B?a.l?a.l[b]:void 0:c&&a.l&&(c=a.l[b],null!=c)?c:a.i[b+a.A]}function K(a,b,c,d=!1,f=!1){f||sa(a);a.g&&(a.g=void 0);b>=a.B||d?(a.l||(a.l=a.i[a.B+a.A]={}))[b]=c:(void 0!==a.l&&a.B>=a.i.length?(d=a.i.length-1,f=b+a.A,f>=d?(a.i[d]=void 0,a.i[f]=c,a.i.push(a.l)):a.i[f]=c):a.i[b+a.A]=c,void 0!==a.l&&b in a.l&&delete a.l[b])} 
function ya(a){var b=J(a,6,!1);{var c=za;let f=!1;var d=null==b||"object"!==typeof b||(f=Array.isArray(b))||b.N!==H?f?new c(b):void 0:b}d!==b&&null!=d&&(K(a,6,d,!1,!0),x(d.i,y(a.i)&-33));b=d;if(null==b)return b;G(b.i)&&!G(a.i)&&(G(b.i)&&(d=Aa(b),d.g=b,b=d),K(a,6,b,!1));return b} 
function Ba(a,b,c,d){sa(a);if(null!=c){var f=[];x(f,1);let e=!1;for(let g=0;g<c.length;g++)f[g]=c[g].i,e=e||G(f[g]);a.u||(a.u={});a.u[b]=c;c=f;e?Object.isExtensible(c)&&(w?c[w]&&(c[w]&=-9):void 0!==c.o&&(c.o&=-9)):x(c,8)}else a.u&&(a.u[b]=void 0),f=ra;K(a,b,f,d)}function L(a,b){return null==a?b:a}function N(a,b){a=J(a,b);return L(null==a?a:!!a,!1)};function Ca(a){if(G(a)&&Object.isFrozen(a))return a;const b=Array.prototype.map.call(a,Da,void 0);z(b,(y(a)|18)&-33);Object.freeze(b);return b}function Ea(a,b){if(null!=a){if(fa&&a instanceof Uint8Array)return a.length?new t(new Uint8Array(a)):ma||(ma=new t(null));if(Array.isArray(a)){if(G(a))return a;b&&(b=y(a),b=!(b&32)&&(!!(b&16)||0===b));return b?(x(a,2),a):va(a,Ea,na)}return a.N===H?Da(a):a}}function Da(a){if(G(a.i))return a;a=Aa(a);x(a.i,2);return a} 
function Aa(a){const b=new a.constructor;a.T&&(b.T=a.T.slice());const c=a.i,d=!!(y(c)&16);for(let h=0;h<c.length;h++){var f=c[h];if(h===c.length-1&&I(f))for(const u in f){var e=+u;if(Number.isNaN(e))(b.l||(b.l=b.i[b.B+b.A]={}))[e]=f[e];else{var g=b,l=f[u],k=d;const v=a.u&&a.u[e];v?Ba(g,e,Ca(v),!0):K(g,e,Ea(l,k),!0)}}else g=b,e=h-a.A,l=d,(k=a.u&&a.u[e])?Ba(g,e,Ca(k),!1):K(g,e,Ea(f,l),!1)}return b};var P=class{constructor(a){null==a&&(a=O);O=null;var b=this.constructor.g||0;const c=0<b;var d=this.constructor.messageId;if(null==a)a=d?[d]:[],x(a,48);else{if(!Array.isArray(a))throw Error();y(a)&16&&z(a,y(a)|32)}c&&0<a.length&&I(a[a.length-1])&&"g"in a[a.length-1]&&(b=0);this.A=(d?0:-1)-b;this.u=void 0;this.i=a;a:{d=this.i.length;b=d-1;if(d&&(d=this.i[b],I(d))){this.l=d;d=Object.keys(d);0<d.length&&Array.prototype.every.call(d,isNaN,void 0)?this.B=Number.MAX_VALUE:this.B=b-this.A;break a}this.B= 
Number.MAX_VALUE}if(!c&&this.l&&"g"in this.l)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');}toJSON(){return va(this.i,wa,xa)}};P.prototype.N=H;P.prototype.toString=function(){return this.i.toString()};let O;var za=class extends P{};var Fa=class extends P{};class Ga{constructor(){this.promise=new Promise(a=>{this.resolve=a})}};function Ha(){const {promise:a,resolve:b}=new Ga;return{promise:a,resolve:b}};/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function Ia(a){var b=window;b.addEventListener&&b.addEventListener("load",a,!1)};function Ja(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})}function Ka(a){return a.replace(RegExp("(^|[\\s]+)([a-z])","g"),function(b,c,d){return c+d.toUpperCase()})};var La=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ma(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}function Na(a=document){return a.createElement("img")};function Oa(a,b){b.google_llp||(b.google_llp={});b=b.google_llp;let c=b[a];if(c)return c;c=Ha();return b[a]=c};async function Pa(){var a=window;const b=[Oa(9,a).promise];try{b.push(Oa(9,a.parent).promise)}catch(c){}return Promise.race(b)};function Q(a){m.google_image_requests||(m.google_image_requests=[]);const b=Na(m.document);b.src=a;m.google_image_requests.push(b)};let Qa=0;function Ra(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)};var Sa=window;function R(a,b,c){if("string"===typeof b)(b=Xa(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var f=b[d],e=Xa(c,d);e&&(c.style[e]=f)}}var Ya={};function Xa(a,b){var c=Ya[b];if(!c){var d=Ja(b);c=d;void 0===a.style[d]&&(d=(ca?"Webkit":ba?"Moz":aa?"ms":null)+Ka(d),void 0!==a.style[d]&&(c=d));Ya[b]=c}return c}function S(a,b){a.style.display=b?"":"none"};class Za{constructor(a,b){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta={}}};const $a=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");var ab=class{constructor(a,b){this.g=a;this.h=b}},bb=class{constructor(a,b){this.url=a;this.U=!!b;this.depth=null}};function T(a,b){const c={};c[a]=b;return[c]}function cb(a,b,c,d,f){const e=[];Ma(a,function(g,l){(g=db(g,b,c,d,f))&&e.push(l+"="+g)});return e.join(b)} 
function db(a,b,c,d,f){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const e=[];for(let g=0;g<a.length;g++)e.push(db(a[g],b,c,d+1,f));return e.join(c[d])}}else if("object"==typeof a)return f=f||0,2>f?encodeURIComponent(cb(a,b,c,d,f+1)):"...";return encodeURIComponent(String(a))}function eb(a){let b=1;for(const c in a.h)b=c.length>b?c.length:b;return 3997-b-a.j.length-1} 
function fb(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;let d=eb(a)-c.length;if(0>d)return"";a.g.sort(function(e,g){return e-g});c=null;let f="";for(let e=0;e<a.g.length;e++){const g=a.g[e],l=a.h[g];for(let k=0;k<l.length;k++){if(!d){c=null==c?g:c;break}let h=cb(l[k],a.j,",$");if(h){h=f+h;if(d>=h.length){d-=h.length;b+=h;f=a.j;break}c=null==c?g:c}}}a="";null!=c&&(a=f+"trn="+c);return b+a}class gb{constructor(){this.j="&";this.h={};this.m=0;this.g=[]}};function hb(){var a=ib,b=window.google_srt;0<=b&&1>=b&&(a.g=b)}function jb(a,b,c,d=!1,f){if((d?a.g:Math.random())<(f||.01))try{let e;c instanceof gb?e=c:(e=new gb,Ma(c,(l,k)=>{var h=e;const u=h.m++;l=T(k,l);h.g.push(u);h.h[u]=l}));const g=fb(e,a.h,"/pagead/gen_204?id="+b+"&");g&&Q(g)}catch(e){}}class kb{constructor(){this.h="http:"===Sa.location.protocol?"http:":"https:";this.g=Math.random()}};let U=null;function lb(){const a=m.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function mb(){const a=m.performance;return a&&a.now?a.now():null};class nb{constructor(a,b){var c=mb()||lb();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.taskId=this.slotId=void 0}};const W=m.performance,ob=!!(W&&W.mark&&W.measure&&W.clearMarks),X=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=ob){var b;if(null===U){U="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(U=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=U;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function pb(a){a&&W&&X()&&(W.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),W.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class qb{constructor(){var a=window;this.h=[];this.j=a||m;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=X()||(null!=b?b:1>Math.random())}start(a,b){if(!this.g)return null;a=new nb(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;W&&X()&&W.mark(b);return a}end(a){if(this.g&&"number"===typeof a.value){a.duration=(mb()||lb())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;W&&X()&&W.mark(b);!this.g||2048< 
this.h.length||this.h.push(a)}}};function rb(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);let d;for(;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n")}catch(d){b=c}}return b} 
function sb(a,b,c){let d,f;try{a.h&&a.h.g?(f=a.h.start(b.toString(),3),d=c(),a.h.end(f)):d=c()}catch(e){c=!0;try{pb(f),c=a.v(b,new Za(e,{message:rb(e)}),void 0,void 0)}catch(g){a.j(217,g)}if(c)window.console?.error?.(e);else throw e;}return d}function tb(a,b){var c=Y;return(...d)=>sb(c,a,()=>b.apply(void 0,d))}function ub(a,b){var c=Y;b.catch(d=>{d=d?d:"unknown rejection";c.j(a,d instanceof Error?d:Error(d),void 0,c.g||void 0)})} 
class vb{constructor(a=null){this.m=ib;this.g=null;this.v=this.j;this.h=a;this.s=!1}pinger(){return this.m}j(a,b,c,d,f){f=f||"jserror";let e;try{const A=new gb;var g=A;g.g.push(1);g.h[1]=T("context",a);b.error&&b.meta&&b.id||(b=new Za(b,{message:rb(b)}));if(b.msg){g=A;var l=b.msg.substring(0,512);g.g.push(2);g.h[2]=T("msg",l)}var k=b.meta||{};b=k;if(this.g)try{this.g(b)}catch(B){}if(d)try{d(b)}catch(B){}d=A;k=[k];d.g.push(3);d.h[3]=k;d=m;k=[];let V;b=null;do{var h=d;try{var u;if(u=!!h&&null!=h.location.href)b:{try{q(h.foo); 
u=!0;break b}catch(B){}u=!1}var v=u}catch{v=!1}v?(V=h.location.href,b=h.document&&h.document.referrer||null):(V=b,b=null);k.push(new bb(V||""));try{d=h.parent}catch(B){d=null}}while(d&&h!=d);for(let B=0,Ta=k.length-1;B<=Ta;++B)k[B].depth=Ta-B;h=m;if(h.location&&h.location.ancestorOrigins&&h.location.ancestorOrigins.length==k.length-1)for(v=1;v<k.length;++v){var E=k[v];E.url||(E.url=h.location.ancestorOrigins[v-1]||"",E.U=!0)}var C=k;let ha=new bb(m.location.href,!1);h=null;const ia=C.length-1;for(E= 
ia;0<=E;--E){var D=C[E];!h&&$a.test(D.url)&&(h=D);if(D.url&&!D.U){ha=D;break}}D=null;const Fb=C.length&&C[ia].url;0!=ha.depth&&Fb&&(D=C[ia]);e=new ab(ha,D);if(e.h){C=A;var F=e.h.url||"";C.g.push(4);C.h[4]=T("top",F)}var ja={url:e.g.url||""};if(e.g.url){var ka=e.g.url.match(La),M=ka[1],Ua=ka[3],Va=ka[4];F="";M&&(F+=M+":");Ua&&(F+="//",F+=Ua,Va&&(F+=":"+Va));var Wa=F}else Wa="";M=A;ja=[ja,{url:Wa}];M.g.push(5);M.h[5]=ja;jb(this.m,f,A,this.s,c)}catch(A){try{jb(this.m,f,{context:"ecmserr",rctx:a,msg:rb(A), 
url:e&&e.g.url},this.s,c)}catch(V){}}return!0}};let ib,Y;const Z=new qb;var wb=()=>{window.google_measure_js_timing||(Z.g=!1,Z.h!=Z.j.google_js_reporting_queue&&(X()&&Array.prototype.forEach.call(Z.h,pb,void 0),Z.h.length=0))};(a=>{ib=a??new kb;"number"!==typeof window.google_srt&&(window.google_srt=Math.random());hb();Y=new vb(Z);Y.g=b=>{var c=Qa;0!==c&&(b.jc=String(c),c=(c=Ra(c,document.currentScript))&&c.getAttribute("data-jc-version")||"unknown",b.shv=c)};Y.s=!0;"complete"==window.document.readyState?wb():Z.g&&Ia(()=>{wb()})})(); 
var xb=(a,b)=>tb(a,b);async function yb(){return Oa(10,m).promise};function zb(a,b=null){a={type:"rewarded",message:a};b&&(a.payload=b);window.parent.postMessage(JSON.stringify(a),"*")};function Ab(){this.K=this.K;this.I=this.I}Ab.prototype.K=!1;function Bb(a,b){a.K?b():(a.I||(a.I=[]),a.I.push(b))};async function Cb(a,b){a.H&&(a.H=!1,document.getElementById("resume-ad-button").removeEventListener("click",a.v),document.getElementById("close-ad-button").removeEventListener("click",a.v),a.P.classList.remove("visible"),a.s.focus());"close-ad-button"===b.target.id?(a.m?.dispatchEvent("confirmationCloseClicked"),(await a.D).dismiss(6)):a.m?.dispatchEvent("confirmationResumeClicked")} 
async function Db(a){S(a.J,!1);Eb(a);const b=await a.D;if(N(a.h,9))S(a.s,!1),b.disableDismissListeners(()=>{});else{const c=xb(948,()=>{Gb(a)});b.disableDismissListeners(c);if(N(a.h,5)||N(a.h,7))a.s.addEventListener("click",c),Bb(a,()=>{a.s.removeEventListener("click",c)})}b.addViewListener(()=>{a.s.focus();a.m?.dispatchEvent("skipShown");-1!==a.j&&(a.R=setInterval(()=>{var c=Hb(a);ub(1012,c)},1E3))})} 
function Ib(a){const b=.066*a.F+"px";R(document.getElementById("close-confirmation-dialog"),"width",.78*a.F+"px");R(document.getElementById("confirmation-title"),{"font-size":.031*a.g+"px","margin-top":.0375*a.g+"px","margin-left":b,"margin-right":b});R(document.getElementById("confirmation-message"),{"font-size":.025*a.g+"px","margin-bottom":.0375*a.g+"px","margin-top":.0375*a.g+"px","margin-left":b,"margin-right":b});R(document.getElementById("confirmation-buttons"),{"font-size":.0218*a.g+"px", 
"line-height":.05625*a.g+"px","margin-right":.0125*a.g+"px","margin-bottom":.0125*a.g+"px"});R(document.getElementById("close-ad-button"),{"padding-left":.044*a.F+"px","padding-right":.044*a.F+"px"});R(document.getElementById("resume-ad-button"),{"padding-left":.044*a.F+"px","padding-right":.044*a.F+"px"})} 
function Eb(a){var b=a.W;a=L(J(a.h,1),"").replace("%1$d",(a.j-a.G).toFixed(0));if("textContent"in b)b.textContent=a;else if(3==b.nodeType)b.data=String(a);else if(b.firstChild&&3==b.firstChild.nodeType){for(;b.lastChild!=b.firstChild;)b.removeChild(b.lastChild);b.firstChild.data=String(a)}else{for(var c;c=b.firstChild;)b.removeChild(c);b.appendChild((9==b.nodeType?b:b.ownerDocument||b.document).createTextNode(String(a)))}} 
async function Gb(a){N(a.h,7)&&!N(a.h,8)?(a.m?.dispatchEvent("skip"),(await a.D).dismiss(1)):N(a.h,5)&&(0>=a.j-a.G&&-1!==a.j?(a.m?.dispatchEvent("abandon"),(await a.D).dismiss(7)):Jb(a))}async function Hb(a){a.H||document.hidden||a.M||(a.G++,0<a.j-a.G?Eb(a):0>=a.j-a.G&&await Kb(a))} 
function Jb(a){a.H=!0;a.m?.dispatchEvent("confirmationDialogueShown");a.P.classList.add("visible");const b=document.getElementById("resume-ad-button");b.addEventListener("click",a.v);const c=document.getElementById("close-ad-button");c.addEventListener("click",a.v);c.focus();Bb(a,()=>{b.removeEventListener("click",a.v);c.removeEventListener("click",a.v)})} 
async function Kb(a){S(a.V,!1);S(a.s,!1);S(a.J,!0);(await a.D).enableDismissListeners();a.J.addEventListener("click",()=>{a.m?.dispatchEvent("abandon")});clearInterval(a.R);N(a.C,1)&&(Lb(a.L),zb("granted",{type:L(J(a.C,2),""),amount:L(J(a.C,3),0)}));const b=yb().then(c=>{c.grantReward()});ub(1011,b)} 
class Mb extends Ab{constructor(a){super();this.h=a;this.C=ya(a)??new za;this.W=document.getElementById("count-down-text");this.j=L(J(a,2),0);this.V=document.getElementById("count-down-container");this.s=document.getElementById("close-button");this.J=document.getElementById("dismiss-button-element");this.P=document.getElementById("dialog-wrapper");this.G=0;this.m=null;this.H=this.M=!1;this.R=0;this.g=Math.max(L(J(a,3),0),L(J(a,4),0));this.F=Math.min(L(J(a,3),0),L(J(a,4),0));this.L=null;this.D=Pa(); 
N(this.C,1)&&(this.L=new Nb(L(J(this.C,4),"")),this.D.then(b=>{b.addViewListener(()=>{var c=this.L;if(!c.h){for(const d of c.j)Q(d);c.h=!0}})}));this.v=xb(949,b=>{Cb(this,b)});Db(this);N(this.h,5)&&Ib(this);N(this.C,1)&&zb("prefetched")}init(a,b){this.m=b;a<this.j&&(this.j=a,Eb(this))}pauseTimer(){this.M=!0}resumeTimer(){this.M=!1}}function Lb(a){const b=(a.g[0]||"").includes("admob_mediation_reward_video_complete")?0:1,c=a.g[(b+1)%2]||"";Q(a.g[b]||"");Q(c)} 
class Nb extends Ab{constructor(a){super();a=JSON.parse(a||"{}");this.h=!1;this.j=a.video_start_urls||[];this.g=a.video_complete_urls||[]}};Qa=94;const Ob=Ra(94,document.currentScript);if(null==Ob)throw Error("JSC not found 94");const Pb={},Qb=Ob.attributes;for(let a=Qb.length-1;0<=a;a--){const b=Qb[a].name;0===b.indexOf("data-jcp-")&&(Pb[b.substring(9)]=Qb[a].value)}(a=>{sb(Y,1010,()=>{var b=a.config;if(null==b||""==b)b=new Fa;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);x(b,16);O=b;b=new Fa(b);O=null}b=new Mb(b);var c=window;c.countdownHandler||(c.countdownHandler=Ha());c.countdownHandler.resolve(b)})})(Pb);}).call(this);
