(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var m=this||self;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}} 
function n(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?n=aa:n=ba;return n.apply(null,arguments)};function p(a){p[" "](a);return a}p[" "]=function(){};var ca={},q=null;var da="undefined"!==typeof Uint8Array;const r=Symbol(void 0);function y(a,b){Object.isFrozen(a)||(r?a[r]|=b:void 0!==a.o?a.o|=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function z(a){let b;r?b=a[r]:b=a.o;return null==b?0:b};var ea={};function D(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var fa=Object,ha=fa.freeze,ia=[];y(ia,3);ha.call(fa,ia);function na(a,b,c,d){if(null!=a){if(Array.isArray(a))a=oa(a,b,c,void 0!==d);else if(D(a)){const e={};for(let f in a)e[f]=na(a[f],b,c,d);a=e}else a=b(a,d);return a}}function oa(a,b,c,d){d=d?!!(z(a)&16):void 0;const e=Array.prototype.slice.call(a);c(a,e);for(a=0;a<e.length;a++)e[a]=na(e[a],b,c,d);return e} 
function pa(a){if(a.Y===ea)a=a.toJSON();else a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&da&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!q){q={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ca[e]=f;for(var g=0;g<f.length;g++){var k=f[g];void 0===q[k]&&(q[k]=g)}}}b=ca[b];c=Array(Math.floor(a.length/3));d= 
b[64]||"";for(e=f=0;f<a.length-2;f+=3){var l=a[f],h=a[f+1];k=a[f+2];g=b[l>>2];l=b[(l&3)<<4|h>>4];h=b[(h&15)<<2|k>>6];k=b[k&63];c[e++]=g+l+h+k}g=0;k=d;switch(a.length-f){case 2:g=a[f+1],k=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+k+d}a=c.join("")}}return a}function qa(){};function E(a,b){return-1===b?null:b>=a.j?a.i?a.i[b]:void 0:a.g[b+a.l]}function ra(a){a=E(a,13);return null==a?a:+a}function sa(a){a=E(a,5);return null==a?0:a}function F(a,b){return null==a?b:a}function G(a,b){return F(E(a,b),"")}function H(a,b){a=E(a,b);return F(null==a?a:!!a,!1)}function I(a){return F(E(a,12),0)};function ta(a){var b=ua;if(null==a||""==a)return new b;a=JSON.parse(a);if(!Array.isArray(a))throw Error(void 0);y(a,16);J=a;b=new b(a);J=null;return b} 
var va=class{constructor(a){null==a&&(a=J);J=null;var b=this.constructor.g||0;const c=0<b;var d=this.constructor.messageId;if(null==a)a=d?[d]:[],y(a,48);else{if(!Array.isArray(a))throw Error();if(z(a)&16){var e=a,f=z(a)|32;r?e[r]=f:void 0!==e.o?e.o=f:Object.defineProperties(e,{o:{value:f,configurable:!0,writable:!0,enumerable:!1}})}}c&&0<a.length&&D(a[a.length-1])&&"g"in a[a.length-1]&&(b=0);this.l=(d?0:-1)-b;this.g=a;a:{d=this.g.length;b=d-1;if(d&&(d=this.g[b],D(d))){this.i=d;d=Object.keys(d);0< 
d.length&&Array.prototype.every.call(d,isNaN,void 0)?this.j=Number.MAX_VALUE:this.j=b-this.l;break a}this.j=Number.MAX_VALUE}if(!c&&this.i&&"g"in this.i)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');}toJSON(){return oa(this.g,pa,qa)}};va.prototype.Y=ea;va.prototype.toString=function(){return this.g.toString()};let J;var ua=class extends va{};function wa(a=window){return a};var K=window;/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function L(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)}function M(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};var xa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ya(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}let N=[];const za=()=>{const a=N;N=[];for(const b of a)try{b()}catch{}};var Aa=(a,b)=>{"complete"===a.readyState||"interactive"===a.readyState?(N.push(b),1==N.length&&(window.Promise?Promise.resolve().then(za):window.setImmediate?setImmediate(za):setTimeout(za,0))):a.addEventListener("DOMContentLoaded",b)};function Ba(a=document){return a.createElement("img")};function Ca(a,b,c=null,d=!1){Da(a,b,c,d)}function Da(a,b,c,d){a.google_image_requests||(a.google_image_requests=[]);const e=Ba(a.document);if(c||d){const f=g=>{c&&c(g);if(d){g=a.google_image_requests;const k=Array.prototype.indexOf.call(g,e,void 0);0<=k&&Array.prototype.splice.call(g,k,1)}M(e,"load",f);M(e,"error",f)};L(e,"load",f);L(e,"error",f)}e.src=b;a.google_image_requests.push(e)};let Ea=0;function Fa(a){return(a=Ka(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function Ka(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)};class La{constructor(a,b){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta={}}};const Ma=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");var Na=class{constructor(a,b){this.g=a;this.i=b}},Oa=class{constructor(a,b){this.url=a;this.X=!!b;this.depth=null}};function P(a,b){const c={};c[a]=b;return[c]}function Pa(a,b,c,d,e){const f=[];ya(a,function(g,k){(g=Qa(g,b,c,d,e))&&f.push(k+"="+g)});return f.join(b)} 
function Qa(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const f=[];for(let g=0;g<a.length;g++)f.push(Qa(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Pa(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}function Ra(a){let b=1;for(const c in a.i)b=c.length>b?c.length:b;return 3997-b-a.j.length-1} 
function Sa(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;let d=Ra(a)-c.length;if(0>d)return"";a.g.sort(function(f,g){return f-g});c=null;let e="";for(let f=0;f<a.g.length;f++){const g=a.g[f],k=a.i[g];for(let l=0;l<k.length;l++){if(!d){c=null==c?g:c;break}let h=Pa(k[l],a.j,",$");if(h){h=e+h;if(d>=h.length){d-=h.length;b+=h;e=a.j;break}c=null==c?g:c}}}a="";null!=c&&(a=e+"trn="+c);return b+a}class Ta{constructor(){this.j="&";this.i={};this.l=0;this.g=[]}};function Ua(){var a=Q,b=window.google_srt;0<=b&&1>=b&&(a.g=b)}function Va(a,b,c,d=!1,e){if((d?a.g:Math.random())<(e||.01))try{let f;c instanceof Ta?f=c:(f=new Ta,ya(c,(k,l)=>{var h=f;const t=h.l++;k=P(l,k);h.g.push(t);h.i[t]=k}));const g=Sa(f,a.i,"/pagead/gen_204?id="+b+"&");g&&Ca(m,g)}catch(f){}}class Wa{constructor(){this.i="http:"===K.location.protocol?"http:":"https:";this.g=Math.random()}};let R=null;function Xa(){const a=m.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function Ya(){const a=m.performance;return a&&a.now?a.now():null};class Za{constructor(a,b){var c=Ya()||Xa();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.taskId=this.slotId=void 0}};const S=m.performance,$a=!!(S&&S.mark&&S.measure&&S.clearMarks),T=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=$a){var b;if(null===R){R="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(R=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=R;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function ab(a){a&&S&&T()&&(S.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),S.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class bb{constructor(){var a=window;this.i=[];this.j=a||m;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.i=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=T()||(null!=b?b:1>Math.random())}start(a,b){if(!this.g)return null;a=new Za(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;S&&T()&&S.mark(b);return a}end(a){if(this.g&&"number"===typeof a.value){a.duration=(Ya()||Xa())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;S&&T()&&S.mark(b);!this.g||2048< 
this.i.length||this.i.push(a)}}};function cb(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);let d;for(;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n")}catch(d){b=c}}return b} 
function db(a,b,c){let d,e;try{a.i&&a.i.g?(e=a.i.start(b.toString(),3),d=c(),a.i.end(e)):d=c()}catch(f){c=!0;try{ab(e),c=a.m(b,new La(f,{message:cb(f)}),void 0,void 0)}catch(g){a.D(217,g)}if(c)window.console?.error?.(f);else throw f;}return d}function eb(a,b){var c=U;return(...d)=>db(c,a,()=>b.apply(void 0,d))}function fb(a){var b=U;a.catch(c=>{c=c?c:"unknown rejection";b.D(967,c instanceof Error?c:Error(c),void 0,b.g||void 0)})} 
class gb{constructor(a=null){this.j=Q;this.g=null;this.m=this.D;this.i=a;this.l=!1}pinger(){return this.j}D(a,b,c,d,e){e=e||"jserror";let f;try{const u=new Ta;var g=u;g.g.push(1);g.i[1]=P("context",a);b.error&&b.meta&&b.id||(b=new La(b,{message:cb(b)}));if(b.msg){g=u;var k=b.msg.substring(0,512);g.g.push(2);g.i[2]=P("msg",k)}var l=b.meta||{};b=l;if(this.g)try{this.g(b)}catch(v){}if(d)try{d(b)}catch(v){}d=u;l=[l];d.g.push(3);d.i[3]=l;d=m;l=[];let V;b=null;do{var h=d;try{var t;if(t=!!h&&null!=h.location.href)b:{try{p(h.foo); 
t=!0;break b}catch(v){}t=!1}var A=t}catch{A=!1}A?(V=h.location.href,b=h.document&&h.document.referrer||null):(V=b,b=null);l.push(new Oa(V||""));try{d=h.parent}catch(v){d=null}}while(d&&h!=d);for(let v=0,Ga=l.length-1;v<=Ga;++v)l[v].depth=Ga-v;h=m;if(h.location&&h.location.ancestorOrigins&&h.location.ancestorOrigins.length==l.length-1)for(A=1;A<l.length;++A){var B=l[A];B.url||(B.url=h.location.ancestorOrigins[A-1]||"",B.X=!0)}var w=l;let ja=new Oa(m.location.href,!1);h=null;const ka=w.length-1;for(B= 
ka;0<=B;--B){var x=w[B];!h&&Ma.test(x.url)&&(h=x);if(x.url&&!x.X){ja=x;break}}x=null;const wb=w.length&&w[ka].url;0!=ja.depth&&wb&&(x=w[ka]);f=new Na(ja,x);if(f.i){w=u;var C=f.i.url||"";w.g.push(4);w.i[4]=P("top",C)}var la={url:f.g.url||""};if(f.g.url){var ma=f.g.url.match(xa),O=ma[1],Ha=ma[3],Ia=ma[4];C="";O&&(C+=O+":");Ha&&(C+="//",C+=Ha,Ia&&(C+=":"+Ia));var Ja=C}else Ja="";O=u;la=[la,{url:Ja}];O.g.push(5);O.i[5]=la;Va(this.j,e,u,this.l,c)}catch(u){try{Va(this.j,e,{context:"ecmserr",rctx:a,msg:cb(u), 
url:f&&f.g.url},this.l,c)}catch(V){}}return!0}};class hb{};let Q,U;const W=new bb;var ib=()=>{window.google_measure_js_timing||(W.g=!1,W.i!=W.j.google_js_reporting_queue&&(T()&&Array.prototype.forEach.call(W.i,ab,void 0),W.i.length=0))};(a=>{Q=a??new Wa;"number"!==typeof window.google_srt&&(window.google_srt=Math.random());Ua();U=new gb(W);U.g=b=>{const c=Ea;0!==c&&(b.jc=String(c),b.shv=Fa(c))};U.l=!0;"complete"==window.document.readyState?ib():W.g&&L(window,"load",()=>{ib()})})(); 
var X=(a,b)=>eb(a,b),jb=(a,b,c)=>{var d=hb,e="W";d.W&&d.hasOwnProperty(e)||(e=new d,d.W=e);d=[];!b.eid&&d.length&&(b.eid=d.toString());Va(Q,a,b,!0,c)};class kb{constructor(){this.promise=new Promise(a=>{this.resolve=a})}};function lb(a,b){b.google_llp||(b.google_llp={});b=b.google_llp;let c=b[a];if(c)return c;const {promise:d,resolve:e}=new kb;c={promise:d,resolve:e};return b[a]=c};async function mb(){return lb(10,m).promise};function Y(a,b,c={}){c.msg_type=b;c.googMsgType="sth";b=JSON.stringify(c);a.parent.postMessage(b,"*")}function nb(a){if(a.G||H(a.i,2))return!0;let b=!0;const c=ob(a);c&&(b=36E5<=c);if(b)try{a.g.localStorage.removeItem("LAST_INTERSTITIAL_TIME")}catch(d){}return b}function Z(a,b,c){G(a.i,3)&&(b.qid=G(a.i,3));G(a.i,10)&&(b.eid=G(a.i,10));b.rtype=I(a.i);b.req=K.location.href;jb(a.P(),b,c)} 
function ob(a){try{const b=+a.g.localStorage.getItem("LAST_INTERSTITIAL_TIME"),c=Date.now();if(b&&b<c)return c-b}catch(b){}return null} 
var pb=class{constructor(a,b,c){this.g=K;this.m=a;this.v=!1;this.B=null;this.s=0;this.i=b;this.G=H(this.i,11)||10===I(this.i)||11===I(this.i);this.j=c;c?.enableCustomCloseButton()}P(){}J(){(this.v=nb(this))?(this.K(),G(this.i,1)&&this.g.parent.postMessage(G(this.i,1),"*")):this.j?.notifyError("freq_cap")}A(){if(!this.s){this.B&&M(this.g,"storage",this.B);this.s=Date.now();if(!H(this.i,2)&&!this.G)try{this.g.localStorage.setItem("LAST_INTERSTITIAL_TIME",""+this.s)}catch(b){}this.V();if(this.m){var a= 
this.g.document.createEvent("Event");a.initEvent("i-creative-view",!0,!1);this.m.dispatchEvent(a);a=this.g.document.createEvent("Event");a.initEvent("onshow",!0,!1);this.g.dispatchEvent(a)}}}H(){}K(){let a=!1;if(this.j){const b=this.j.waitForOnShow().then(()=>{this.A();for(const c of this.m.document.getElementsByClassName("GoogleActiveViewElement"))c.removeAttribute("data-google-av-dm")});fb(b);this.j.listenToBackButton(()=>{this.H()})}else this.g.IntersectionObserver&&.01<F(ra(this.i),0)&&(a=!0, 
(new this.g.IntersectionObserver((b,c)=>{b.forEach(d=>{if(!(0>=d.intersectionRatio)){this.A();for(const e of this.m.document.getElementsByClassName("GoogleActiveViewElement"))e.removeAttribute("data-google-av-dm");c.disconnect()}})},{threshold:F(ra(this.i),0)})).observe(this.g.document.documentElement));L(this.g,"message",X(262,b=>{a:{var c=a;if(b&&(this.g.parent==b.source||this.g.parent.parent==b.source)){var d={};try{d=this.g.JSON.parse(b.data)}catch(e){b=void 0;break a}switch(d?.msg_type){case "i-view":this.v&& 
!c&&this.A();Z(this,{type:"viewmsg",has_iobs:!!this.g.IntersectionObserver});break;case "r-back-button":null==this.j&&this.H()}}b=void 0}return b}));this.G||(this.B=X(263,()=>{this.v=nb(this);if(!this.v){var b={i_tslv:ob(this)};Y(this.g,"i-no",b)}}),L(this.g,"storage",this.B));this.j||Y(this.g,"i-adframe-load")}V(a){let b;try{const c=wa(this.m);c.vv?c.vv():b=!0}catch(c){U.D(533,c,void 0,void 0);return}a=a||1;b?(Z(this,{vf:a}),3<=a||this.g.setTimeout(n(pb.prototype.V,this,a+1),3E3)):1<a&&Z(this,{vs:a})}};function qb(a){window.parent.postMessage(JSON.stringify({type:"rewarded",message:a}),"*")};var rb=a=>{a=a.document;let b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}};function sb(a,b,c){jb("jserror",{context:"iaf::itf",req:K.location.href,db:a?1:0,ls:b?1:0,eid:G(c,10),qid:G(c,3),rtype:I(c)})}function tb(a,b){ub(a,b)&&(a.l.style.background="rgba(192,192,192, .3)",m.setTimeout(()=>{a.l.style.background="transparent";a.dismiss(2)},750))}function vb(a,b){b.some(c=>"intervention"===c.type&&"HeavyAdIntervention"===c.body?.id)&&(Z(a,{hai:"1"},1),a.s?a.dismiss(8):a.j?a.j.notifyError("heavy_ads"):Y(a.g,"i_iif"))} 
function xb(a){const b=X(259,n(function(){Y(this.g,"i-blur");M(this.g,"blur",b)},a));L(a.g,"blur",b)}function yb(a){a.u||0===a.s||(a.l.setAttribute("aria-label",G(a.i,7)),a.l.setAttribute("role","button"),a.l.setAttribute("tabindex","0"),a.l.focus())}function zb(a,b){H(a.i,15)?(qb("canceled"),qb("closed")):a.j?a.j.closeAd():Y(a.g,b)} 
function Ab(a,b){const c=a.g.document.getElementById("creative");a.g.goog_vignette_survey&&(a.g.goog_vignette_survey.display(c,()=>{a.dismiss(3)},()=>{},1),b&&b.stopPropagation())}function Bb(a){!1===a.u&&a.enableDismissListeners();a.U&&L(a.U,"click",X(261,c=>Ab(a,c)));const b=a.g.document.getElementById("card");b&&b.addEventListener("click",X(909,c=>{c?.stopPropagation()}))} 
function Cb(a){L(a.g,"resize",()=>{var b=a.g;b=b.innerHeight>=b.innerWidth?1:2;a.I?(a.I=!1,a.M=2===b):(a.M?1===b:2===b)&&a.dismiss(4)})}function Db(a){a.g.addEventListener("message",b=>{if(b.source===a.m)try{const c=JSON.parse(b.data);"rewarded"===c.type&&"closed"===c.message&&a.dismiss(11===I(a.i)?6:1)}catch(c){}})} 
function ub(a,b){if(!b)return!0;if((b.preventDefault?b.defaultPrevented:!1===b.returnValue)||b.target&&b.target.ownerDocument==a.m.document)return!1;for(a=b.target;a;){if("creative"==a.id)return!1;a=a.parentElement}return!0} 
var Eb=class extends pb{constructor(a,b,c,d,e){super(a,d,e);this.l=b;this.U=c;this.N=0;this.T=X(260,f=>{this.dismiss(1);f&&f.stopPropagation()});this.R=f=>tb(this,f);this.L=[];this.F=[];this.u=!1;this.O=()=>{};this.I=this.M=!1;this.C=null}J(){super.J();(this.C=this.g.ReportingObserver?new this.g.ReportingObserver((a,b)=>{vb(this,a)&&b.disconnect()},{buffered:!0}):null)&&L(this.g,"pagehide",()=>{vb(this,this.C.takeRecords());this.C.disconnect()})}P(){return"ia_evt"}H(){this.u?this.O():this.dismiss(9)}addViewListener(a){a= 
eb(483,a);this.s?a():this.L.push(a)}addDismissListener(a){this.F.push(eb(484,a))}disableDismissListeners(a){this.u=!0;this.O=a;M(this.l,"click",this.T);M(this.g.document,"click",this.R)}enableDismissListeners(){this.u=!1;L(this.l,"click",this.T);L(this.g.document,"click",this.R);yb(this)}dismiss(a){document.body.setAttribute("aria-hidden","true");Z(this,{ttd:Date.now()-this.s,req:K.location.href,pda:this.N,ds:a,idrw:H(this.i,15)?1:0});this.N++||xb(this);let b=0;for(let d=0;d<this.F.length;d++)b=Math.max(b, 
this.F[d]());b=Math.min(b,1E3);let c="i-dismiss";6===a?c="r-dismiss-before-reward":7===a&&(c="r-dismiss-after-reward");0===b?zb(this,c):m.setTimeout(()=>zb(this,c),b)}K(){super.K();Bb(this)}A(){super.A();var a=this.g;this.M=2===(a.innerHeight>=a.innerWidth?1:2);this.I=0===this.g.innerWidth&&0===this.g.innerHeight;Cb(this);yb(this);var b=this.l.getBoundingClientRect(),c=b.bottom,d=b.right;a=rb(this.g).clientHeight;var e=rb(this.g).clientWidth,f=Math.floor(c-a);const g=Math.floor(d-e);if(0<=f||5<g)c-= 
b.top,d-=b.left,b=this.g,Z(this,{dhb:f>=c?1:0,dhr:g>=d?1:0,h:a,w:e,bh:c,bw:d,opb:f,opr:g,pt:b.innerHeight>=b.innerWidth?1:0,req:this.g.location.href});document.getElementById("ad_iframe").contentWindow.postMessage(JSON.stringify({type:"rewarded",message:"visible"}),"*");for(a=0;a<this.L.length;a++)this.L[a]();Db(this);if(!(.01<Math.random())){a=Ka(24,document.currentScript);a=`https://${a&&"true"===a.getAttribute("data-jc-rcd")?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${24}&version=${Fa(24)}&sample=${.01}`; 
e=window;if(f=e.navigator)f=e.navigator.userAgent,f=/Chrome/.test(f)&&!/Edge/.test(f)?!0:!1;f&&e.navigator.sendBeacon?e.navigator.sendBeacon(a):Ca(e,a,void 0,!1)}a=this.g.navigator?!0===this.g.navigator.standalone:!1;e=window.matchMedia("(display-mode: standalone)").matches;Z(this,{wapp:a||e})}};Ea=24;const Fb=Ka(24,document.currentScript);if(null==Fb)throw Error("JSC not found 24");const Gb={},Hb=Fb.attributes;for(let a=Hb.length-1;0<=a;a--){const b=Hb[a].name;0===b.indexOf("data-jcp-")&&(Gb[b.substring(9)]=Hb[a].value)} 
(async function(a){const b=ta(a.config),c=X(258,async()=>{var d=null;H(b,25)&&(d=await mb());{var e=document.getElementById("ad_iframe").contentWindow;var f=K.document;const g=e.document,k=sa(b),l=0===k||2===k?g.getElementById(G(b,6)):f.getElementById(G(b,6));f=0===k?g.getElementById(G(b,8)):f.getElementById(G(b,8));let h;try{h=!!K.localStorage}catch(t){}l?(h||sb(l,h,b),e=new Eb(e,l,f,b,d),e.J()):(sb(l,h,b),d?d.notifyError("no_dismiss_button"):Y(K,"i_iif"),e=null)}window.interstitialAdFrame=e;lb(9, 
window).resolve(e)});0===sa(b)||2===sa(b)||H(b,16)?(a=document.getElementById("ad_iframe"),null!=a.contentDocument?Aa(a.contentDocument,()=>void c()):document.getElementById("ad_iframe").addEventListener("load",c)):c()})(Gb);}).call(this);
